//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.FirstName = new Name();
            this.LastName = new Name();
        }
    
        public short Age { get; set; }
        public int Id { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public Name FirstName { get; set; }
        public Name LastName { get; set; }
    
        public virtual Title Title { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
